package com.proyecto404.finalProjectJP.core.useCases.exceptions

class RepeatedUsernameError : Throwable() {

}
