package com.proyecto404.finalProjectJP.core.domain.useCases.exceptions

class RepeatedUsernameError : Throwable() {

}
